/**
 * The Pigma collaboration relay: a room relay plus a last-snapshot per room.
 *
 * There is no identity layer here. No accounts, no sessions, no roles, no user
 * storage, no auth endpoints — a participant is a random `clientId` generated by
 * their own client plus a nickname that is echoed to other clients for cursor
 * labels and never persisted. The only access control is an optional room token
 * in the URL, the same spirit as the MCP relay token.
 *
 * HTTP surface, deliberately tiny:
 *   GET /collab?room=<id>&token=<token>   WebSocket upgrade (the relay)
 *   GET /health                           liveness + room count
 *   GET /<asset>                          built static assets (no SPA fallback)
 *   anything else                         404
 *
 * Snapshots: one JSON file per room under `dataDir`, written atomically. It
 * contains the document blob a client sent, nothing else.
 */
import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import { readFile, rename, rm, writeFile, mkdir } from 'node:fs/promises';
import { join, normalize, resolve, extname, sep } from 'node:path';
import { timingSafeEqual } from 'node:crypto';
import type { Duplex } from 'node:stream';
import { decodeClientMessage, encodeMessage, type ServerMessage } from './protocol';
import { RoomRegistry, type Snapshot } from './room';
import { RateLimiter, resolveLimits, type RelayLimits } from './limits';
import { acceptWebSocket, isWebSocketUpgrade, type WebSocketConnection } from './websocket';

export interface CollabServerOptions {
  /** Directory of built static assets to serve. Omitted: only the relay + /health. */
  staticDir?: string;
  /** Directory for one snapshot file per room. Omitted: snapshots stay in memory. */
  dataDir?: string;
  /** Optional room token required on the WebSocket URL. */
  token?: string;
  maxPayloadBytes?: number;
  /** Capacity and rate bounds. Defaults come from `DEFAULT_LIMITS`. */
  limits?: Partial<RelayLimits>;
  now?: () => number;
  /**
   * Extra HTTP routes, tried before the relay's own. A deployment uses this to
   * mount the MCP endpoint and the config surface on the same port; returning
   * `true` means the request was handled.
   */
  handle?: (request: IncomingMessage, response: ServerResponse) => boolean;
}

/** Counters exposed by `/health` and `/metrics`. Never identify anyone. */
export interface RelayMetrics {
  /** Snapshot writes that failed (a broken data dir must not crash the relay). */
  snapshotWriteFailures: number;
  connectionsTotal: number;
  connectionsRejected: number;
  peersRejected: number;
  /** Document payloads refused because an E2E room received plaintext. */
  plaintextRejected: number;
  messagesIn: number;
  messagesOut: number;
  rateLimited: number;
  snapshotsStored: number;
  snapshotsExpired: number;
  roomsSwept: number;
}

export interface CollabServer {
  readonly server: Server;
  readonly rooms: RoomRegistry;
  readonly limits: RelayLimits;
  listen(port?: number, host?: string): Promise<{ port: number; host: string }>;
  close(): Promise<void>;
  /** Test/inspection helper: snapshot currently held for a room. */
  snapshotOf(roomId: string): Snapshot | null;
  /** Run the GC pass now (the same one the interval runs). Returns what it dropped. */
  sweepNow(): Promise<{ rooms: string[]; snapshots: string[] }>;
}

const MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.webp': 'image/webp',
  '.woff2': 'font/woff2',
  '.ico': 'image/x-icon',
  '.map': 'application/json; charset=utf-8',
};

/** Room ids become file names, so keep them to a safe, boring alphabet. */
export function safeRoomId(raw: string | null): string {
  const value = (raw ?? '').trim().slice(0, 128);
  const cleaned = value.replace(/[^A-Za-z0-9._-]/g, '_');
  return cleaned.length > 0 ? cleaned : 'default';
}

function tokenMatches(expected: string, provided: string | null): boolean {
  if (provided === null) return false;
  const a = Buffer.from(expected);
  const b = Buffer.from(provided);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

export function createCollabServer(options: CollabServerOptions = {}): CollabServer {
  const sockets = new Map<string, { roomId: string; connection: WebSocketConnection }>();
  /** Every accepted connection, including ones that never sent `hello`. */
  const connections = new Set<WebSocketConnection>();
  /** Live sockets per IP, for the per-IP connection cap. */
  const perIp = new Map<string, number>();
  const snapshots = new Map<string, Snapshot>();
  /** When each snapshot was stored; the on-disk blob stays `{ file, seq }`. */
  const storedAt = new Map<string, number>();
  /**
   * Snapshot writes in flight. Tracked so `close()` can drain them: a write that
   * outlives the caller would otherwise race a directory removal and, because it
   * was floating, surface as an unhandled rejection.
   */
  const writes = new Set<Promise<void>>();
  const dataDir = options.dataDir ? resolve(options.dataDir) : undefined;
  const staticDir = options.staticDir ? resolve(options.staticDir) : undefined;
  const limits = resolveLimits(options.limits);
  const now = options.now ?? Date.now;
  const startedAt = now();

  const metrics: RelayMetrics = {
    snapshotWriteFailures: 0,
    connectionsTotal: 0,
    connectionsRejected: 0,
    peersRejected: 0,
    plaintextRejected: 0,
    messagesIn: 0,
    messagesOut: 0,
    rateLimited: 0,
    snapshotsStored: 0,
    snapshotsExpired: 0,
    roomsSwept: 0,
  };

  const connectionLimiter = new RateLimiter({ limit: limits.connectionAttemptsPerMinute, windowMs: 60_000, now });
  const messageLimiter = new RateLimiter({ limit: limits.messagesPerWindow, windowMs: limits.messageWindowMs, now });

  const send = (clientId: string, message: ServerMessage): void => {
    const entry = sockets.get(clientId);
    if (!entry) return;
    metrics.messagesOut += 1;
    entry.connection.send(encodeMessage(message));
  };
  const rooms = new RoomRegistry(send, {
    now,
    load: (roomId) => {
      // A snapshot past its TTL is already gone as far as any client is concerned.
      if (expired(roomId)) return null;
      return snapshots.get(roomId) ?? null;
    },
  });

  function expired(roomId: string): boolean {
    const at = storedAt.get(roomId);
    return at !== undefined && now() - at >= limits.snapshotTtlMs;
  }

  const persist = (roomId: string, snapshot: Snapshot): void => {
    // The in-memory store is updated synchronously, so readers never wait on disk.
    snapshots.set(roomId, snapshot);
    storedAt.set(roomId, now());
    metrics.snapshotsStored += 1;
    if (!dataDir) return;
    const write = (async () => {
      await mkdir(dataDir, { recursive: true });
      const target = join(dataDir, `${safeRoomId(roomId)}.json`);
      const temp = `${target}.${process.pid}.tmp`;
      await writeFile(temp, JSON.stringify(snapshot));
      await rename(temp, target);
    })()
      // A failed write is counted, never thrown into the void: an unhandled
      // rejection here would take the process down for a disk problem.
      .catch(() => {
        metrics.snapshotWriteFailures += 1;
      })
      .finally(() => {
        writes.delete(write);
      });
    writes.add(write);
  };

  /** Resolve once every in-flight snapshot write has settled. */
  const drainWrites = (): Promise<void> => Promise.all([...writes]).then(() => undefined);

  /**
   * Drop idle rooms and expired snapshots. Never a document store: TTL applies
   * to the in-memory entry and to the file on disk.
   */
  async function sweep(): Promise<{ rooms: string[]; snapshots: string[] }> {
    const at = now();
    const droppedRooms = rooms.sweep(limits.roomTtlMs, at);
    const filesToRemove: string[] = [];
    for (const roomId of droppedRooms) {
      if (snapshots.delete(roomId)) metrics.snapshotsExpired += 1;
      storedAt.delete(roomId);
      filesToRemove.push(safeRoomId(roomId));
    }
    metrics.roomsSwept += droppedRooms.length;

    const expiredSnapshots: string[] = [];
    for (const [roomId, at2] of storedAt) {
      if (at - at2 < limits.snapshotTtlMs) continue;
      snapshots.delete(roomId);
      storedAt.delete(roomId);
      expiredSnapshots.push(roomId);
      metrics.snapshotsExpired += 1;
      filesToRemove.push(safeRoomId(roomId));
    }
    connectionLimiter.prune();
    messageLimiter.prune();

    if (dataDir) {
      await Promise.all(filesToRemove.map((name) => rm(join(dataDir, `${name}.json`), { force: true }).catch(() => undefined)));
    }
    return { rooms: droppedRooms, snapshots: expiredSnapshots };
  }

  const gcTimer = setInterval(() => {
    void sweep();
  }, limits.gcIntervalMs);
  // Never hold the process open just to run GC.
  gcTimer.unref?.();

  const server = createServer((request: IncomingMessage, response: ServerResponse) => {
    void handleHttp(request, response);
  });

  function snapshot(): { ok: true; uptimeMs: number; rooms: number; participants: number; connections: number; snapshots: number; limits: RelayLimits; metrics: RelayMetrics } {
    let participants = 0;
    for (const roomId of rooms.ids()) participants += rooms.get(roomId).peerCount;
    return {
      ok: true,
      uptimeMs: now() - startedAt,
      rooms: rooms.size,
      participants,
      connections: connections.size,
      snapshots: snapshots.size,
      limits,
      metrics,
    };
  }

  /** Prometheus-style text: one line per metric, no dependency. */
  function metricsText(): string {
    const state = snapshot();
    const gauges: Array<[string, string, number]> = [
      ['pigma_uptime_ms', 'Relay uptime in milliseconds', state.uptimeMs],
      ['pigma_rooms', 'Rooms currently held', state.rooms],
      ['pigma_participants', 'Participants currently connected', state.participants],
      ['pigma_connections', 'WebSocket connections currently open', state.connections],
      ['pigma_snapshots', 'Snapshots currently held', state.snapshots],
    ];
    const counters: Array<[string, string, number]> = [
      ['pigma_connections_total', 'Connections accepted since start', metrics.connectionsTotal],
      ['pigma_connections_rejected_total', 'Upgrades refused by a limit', metrics.connectionsRejected],
      ['pigma_peers_rejected_total', 'Joins refused because the room was full', metrics.peersRejected],
      ['pigma_plaintext_rejected_total', 'Plaintext document payloads refused in an encrypted room', metrics.plaintextRejected],
      ['pigma_messages_in_total', 'Client messages processed', metrics.messagesIn],
      ['pigma_messages_out_total', 'Relayed messages sent', metrics.messagesOut],
      ['pigma_rate_limited_total', 'Connections closed by the message rate limit', metrics.rateLimited],
      ['pigma_snapshots_stored_total', 'Snapshots written by clients', metrics.snapshotsStored],
      ['pigma_snapshot_write_failures_total', 'Snapshot writes that failed', metrics.snapshotWriteFailures],
      ['pigma_snapshots_expired_total', 'Snapshots dropped by TTL or room GC', metrics.snapshotsExpired],
      ['pigma_rooms_swept_total', 'Rooms dropped by the sweep', metrics.roomsSwept],
    ];
    const lines: string[] = [];
    for (const [name, help, value] of gauges) {
      lines.push(`# HELP ${name} ${help}`, `# TYPE ${name} gauge`, `${name} ${value}`);
    }
    for (const [name, help, value] of counters) {
      lines.push(`# HELP ${name} ${help}`, `# TYPE ${name} counter`, `${name} ${value}`);
    }
    return `${lines.join('\n')}\n`;
  }

  async function handleHttp(request: IncomingMessage, response: ServerResponse): Promise<void> {
    if (options.handle?.(request, response)) return;
    const url = new URL(request.url ?? '/', 'http://localhost');
    if (url.pathname === '/health') {
      response.writeHead(200, { 'content-type': 'application/json' });
      response.end(JSON.stringify(snapshot()));
      return;
    }
    if (url.pathname === '/metrics') {
      response.writeHead(200, { 'content-type': 'text/plain; version=0.0.4; charset=utf-8' });
      response.end(request.method === 'HEAD' ? undefined : metricsText());
      return;
    }
    if (request.method !== 'GET' && request.method !== 'HEAD') {
      response.writeHead(405, { 'content-type': 'text/plain' });
      response.end('method not allowed');
      return;
    }
    if (!staticDir) {
      notFound(response);
      return;
    }
    // Static assets only. Pigma has no client-side URL routing, so there is no
    // SPA fallback: a path that is not a real file is a 404, which also keeps
    // the no-auth guarantee crisp (there is no route to invent).
    const requested = normalize(decodeURIComponent(url.pathname)).replace(/^(\.\.[/\\])+/, '');
    const candidate = resolve(staticDir, `.${sep}${requested}`);
    const inside = candidate === staticDir || candidate.startsWith(staticDir + sep);
    if (!inside) {
      // Path traversal outside the asset root is a 404, never a file read.
      notFound(response);
      return;
    }
    const target = requested === '/' ? join(staticDir, 'index.html') : candidate;
    const served = await readFile(target).catch(() => null);
    if (!served) {
      notFound(response);
      return;
    }
    response.writeHead(200, {
      'content-type': MIME[extname(target).toLowerCase()] ?? 'application/octet-stream',
      'content-length': served.byteLength,
    });
    response.end(request.method === 'HEAD' ? undefined : served);
  }

  function refuse(socket: Duplex, status: number, message: string): void {
    socket.write(
      `HTTP/1.1 ${status} ${status === 429 ? 'Too Many Requests' : 'Refused'}\r\n` +
        'Connection: close\r\n' +
        'Retry-After: 10\r\n' +
        'content-type: text/plain\r\n' +
        `content-length: ${Buffer.byteLength(message)}\r\n\r\n${message}`,
    );
    socket.destroy();
  }

  function notFound(response: ServerResponse): void {
    response.writeHead(404, { 'content-type': 'application/json' });
    response.end(JSON.stringify({ error: 'not found' }));
  }

  server.on('upgrade', (request: IncomingMessage, socket: Duplex, head: Buffer) => {
    const url = new URL(request.url ?? '/', 'http://localhost');
    if (url.pathname !== '/collab' || !isWebSocketUpgrade(request)) {
      socket.write('HTTP/1.1 404 Not Found\r\nConnection: close\r\n\r\n');
      socket.destroy();
      return;
    }
    if (options.token && !tokenMatches(options.token, url.searchParams.get('token'))) {
      socket.write('HTTP/1.1 401 Unauthorized\r\nConnection: close\r\n\r\n');
      socket.destroy();
      return;
    }

    // Abuse bounds. Both are per IP and deliberately generous; they exist so one
    // address cannot exhaust the relay, not to meter anyone.
    const peerIp = request.socket.remoteAddress ?? 'unknown';
    if (!connectionLimiter.tryConsume(peerIp)) {
      metrics.connectionsRejected += 1;
      refuse(socket, 429, 'too many connection attempts');
      return;
    }
    if ((perIp.get(peerIp) ?? 0) >= limits.maxConnectionsPerIp) {
      metrics.connectionsRejected += 1;
      refuse(socket, 429, 'too many open connections from this address');
      return;
    }
    if (head.length > 0) socket.unshift(head);

    const roomId = safeRoomId(url.searchParams.get('room'));
    const room = rooms.get(roomId);
    let clientId: string | null = null;
    // Release the per-IP slot exactly once, when this connection ends.
    let released = false;
    /** Set once this connection has been closed for exceeding the rate. */
    let rateLimited = false;
    const release = (): void => {
      if (released) return;
      released = true;
      const remaining = (perIp.get(peerIp) ?? 1) - 1;
      if (remaining <= 0) perIp.delete(peerIp);
      else perIp.set(peerIp, remaining);
    };
    const connection = acceptWebSocket(request, socket, {
      maxPayloadBytes: options.maxPayloadBytes,
      handlers: {
        onMessage: (text) => {
          metrics.messagesIn += 1;
          if (!messageLimiter.tryConsume(peerIp)) {
            // Count and close once; later frames of the same burst are dropped.
            if (!rateLimited) {
              rateLimited = true;
              metrics.rateLimited += 1;
              connection.close(1008, 'rate limit exceeded');
            }
            return;
          }
          const message = decodeClientMessage(text);
          if (!message) return;
          if (message.t === 'hello') {
            if (clientId !== null && clientId !== message.clientId) {
              sockets.delete(clientId);
              room.leave(clientId);
            }
            clientId = message.clientId;
            const previous = sockets.get(clientId);
            if (previous) previous.connection.close(1000, 'replaced');
            if (!room.has(clientId) && room.peerCount >= limits.maxRoomPeers) {
              // The cap is on participants, so it is enforced where a peer
              // becomes one (a reconnect for a known id is not a new peer).
              metrics.peersRejected += 1;
              connection.send(encodeMessage({ t: 'error', code: 'room-full', message: `room is full (${limits.maxRoomPeers} participants)` }));
              connection.close(1013, 'room is full');
              return;
            }
            // Register first: the room sends the welcome through this socket.
            sockets.set(clientId, { roomId, connection });
            // The room's mode is fixed by the first participant; a mismatch is
            // refused so a plaintext client can never sit in an encrypted room.
            const violation = room.join(clientId, message.nickname, message.e2e === true);
            if (violation) {
              metrics.plaintextRejected += 1;
              sockets.delete(clientId);
              connection.send(encodeMessage({ t: 'error', code: violation.code, message: violation.message }));
              connection.close(1008, violation.message);
              return;
            }
            return;
          }
          if (clientId === null) {
            connection.send(encodeMessage({ t: 'error', code: 'not-joined', message: 'send hello first' }));
            return;
          }
          const violation = room.handle(clientId, message);
          if (violation) {
            // An encrypted room stores ciphertext or nothing: refuse the payload
            // rather than persisting or forwarding plaintext.
            metrics.plaintextRejected += 1;
            connection.send(encodeMessage({ t: 'error', code: violation.code, message: violation.message }));
            connection.close(1008, violation.message);
            return;
          }
          if (message.t === 'snapshot') persist(roomId, { file: message.file, seq: message.seq });
        },
        onClose: () => {
          connections.delete(connection);
          release();
          if (clientId === null) return;
          const current = sockets.get(clientId);
          if (current?.connection === connection) sockets.delete(clientId);
          room.leave(clientId);
          rooms.prune(roomId);
        },
      },
    });
    // A peer that vanishes without a close handshake (crash, network drop) is
    // otherwise only noticed when TCP gives up. Keepalive makes that bounded.
    (socket as Duplex & { setKeepAlive?: (enable?: boolean, initialDelay?: number) => void }).setKeepAlive?.(true, 30_000);
    connections.add(connection);
    metrics.connectionsTotal += 1;
    perIp.set(peerIp, (perIp.get(peerIp) ?? 0) + 1);
  });

  return {
    server,
    rooms,
    listen: (port = 0, host = '127.0.0.1') =>
      new Promise((resolveListen, rejectListen) => {
        server.once('error', rejectListen);
        server.listen(port, host, () => {
          const address = server.address();
          const actual = typeof address === 'object' && address ? address.port : port;
          resolveListen({ port: actual, host });
        });
      }),
    limits,
    sweepNow: () => sweep(),
    close: async () => {
      clearInterval(gcTimer);
      // Deterministic shutdown: no snapshot write is left in flight, so a caller
      // that removes the data dir afterwards cannot race one.
      await drainWrites();
      // Upgraded sockets are detached from the HTTP server, so close them
      // explicitly or `server.close()` would wait forever.
      for (const connection of connections) connection.close(1001, 'server shutting down');
      connections.clear();
      sockets.clear();
      server.closeAllConnections?.();
      await new Promise<void>((resolveClose) => server.close(() => resolveClose()));
    },
    snapshotOf: (roomId) => snapshots.get(roomId) ?? null,
  };
}
